name: Build and Publish
on:
  push:
    branches:
      - '**'

# env:
  ## SET_NAME - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
    steps:
      - id: set
        run: |
          echo "::set-output name=image::${SET_NAME:-${{ github.event.organization.login }}/${{ github.event.repository.name }}}"
      - uses: hmarr/debug-action@v2
