name: dispatch1
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Hello message'
        required: true
  # push:
  #   branches:
  #     - '**'git p
  #   tags:
  #     - '**'


jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      -
        id: set
        run: |
          echo ${{ github.event.inputs.message }}
          echo "${{ toJSON(github.event) }}"
          echo "::set-output name=empty::"
          echo "::set-output name=nonempty::Foo Bar!"
      - run: |
          echo "${{ steps.set.outputs.empty || 'Hello world!' }}"
          echo "${{ steps.set.outputs.nonempty || 'Hello world!' }}"
