name: Build and Publish
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

# env:
  ## SET_NAME - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
    steps:
      - id: set
        run: |
          echo "::set-output name=image::${SET_NAME:-${{ github.event.organization.login }}/${{ github.event.repository.name }}}"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ needs.pre.outputs.image }}
          tags: |
            type=semver,pattern=v{{version}},priority=910
            type=semver,pattern=v{{version}},value=v1.2.3
