name: dispatch1
on:
  push:
  workflow_dispatch:
    inputs:
      message:
        description: 'Hello message'
        required: true
  # push:
  #   branches:
  #     - '**'git p
  #   tags:
  #     - '**'


jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - run: echo "${{ startsWith(github.ref, 'refs/heads/devops\/refactor-pipeline') }}"
#      - name: Parse semver string
#        id: semver_parser 
#        uses: booxmedialtd/ws-action-parse-semver@v1
#        with:
#          input_string: 'refs/tags/helllo'
#          version_extractor_regex: '\/v(.*)$'
