name: Build and Publish
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

# env:
  ## SET_NAME - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  pre:
    runs-on: ubuntu-latest
    # container:
    #   image: dysnix/kubectl:v1.19-gcloud
    steps:
      -
        run: |
          echo $GITHUB_PATH
          echo "$(pwd)/hello" >> $GITHUB_PATH
          cat $GITHUB_PATH
          mkdir -p hello
          echo 'echo hello' > hello/hello
          chmod 755 hello/hello
          hello || :

      -
        run: |
          echo $GITHUB_PATH
          cat $GITHUB_PATH | grep hello || :
