name: Build and Publish
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

# env:
  ## SET_NAME - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
    steps:
      -
        uses: actions/github-script@v4
        id: set
        with:
          script: |
            // Split tag into a semver and the release id v1.2.3-r1 => v1.2.3 and -r1
            const match = context.ref.match(/^refs\/tags\/(.*)(-r\d+)$/);
            if (match) {
              core.setOutput('semver', match[1]);
              core.setOutput('rid', match[2]);
            }
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor:
            suffix=-foo
          images: hello
          tags: |
            type=semver,pattern=v{{version}},value=${{ steps.set.outputs.semver }}
            type=semver,pattern=v{{version}},value=${{ steps.set.outputs.semver }},suffix=-foo${{ steps.set.outputs.rid }}
            type=raw,value=${{ steps.set.outputs.latestFlavor }},suffix=
