name: dispatch1
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Hello message'
        required: true
  # push:
  #   branches:
  #     - '**'
  #   tags:
  #     - '**'


jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      -
        run: echo
          echo ${{ github.event.inputs.message }}
