name: dispatch1
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Hello message'
        required: true
  # push:
  #   branches:
  #     - '**'git p
  #   tags:
  #     - '**'


jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Parse semver string
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: 'refs/tags/helllo'
          version_extractor_regex: '\/v(.*)$'
