name: Call
on:
  push:

jobs:
#   call:
#     name: Call
#     uses: dysnix/github-workflows/.github/workflows/docker.build-and-push.yaml@switch-to-latestv2

  output:
    name: Output
    runs-on: ubuntu-latest
#     needs: [call]
    steps:
      - run: |
          echo
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
          tags: |
            3.15 3.15.10 latest
