name: Reusable workflow

on:
  workflow_call:
    inputs:
      test-bool:
        required: false
        type: string
        default: true
      test-string:
        required: false
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - uses: hmarr/debug-action@v2
      -
        uses: actions/github-script@v5
        name: test type
        with:
          script: |
            console.log(typeof ${{ inputs.test-bool }})
            console.log("${{ inputs.test-bool }}".toLowerCase())
            console.log("${{ inputs.test-bool == false }}")

      - run: |
          echo '${{ inputs.test-bool }}'
          find /home | grep tgh || /bin/true
          echo "${{ github.ref }}"
          echo "${{ github.repository }}"

      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"
