name: dispatch2
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input version (SemVer) tag of tagref to genarte images for'
        required: false

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  VERSION_REGEX: ^(refs\/tags\/)?v([0-9]+.[0-9]+.[0-9]+(-r[0-9]+)?)$
  # DOCKER_IMAGE - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
      tag: v${{ steps.kubever.outputs.version }}
      version: ${{ steps.kubever.outputs.version }}
      minor_version: ${{ steps.kubever.outputs.minorversion }}
      ## Note!: prerelease (-r\d+) is used as the release id
      release_id: ${{ steps.kubever.outputs.prerelease }}
      push: ${{ steps.kubever.outputs.failed == 'false' }}
    steps:
      -
        uses: actions/github-script@v4
        id: set
        with:
          script: |
            const image = '${{ github.event.repository.full_name }}'.toLowerCase().replace(/\/docker-/, '/')
            core.setOutput('image', '${{ env.DOCKER_IMAGE }}' ? '${{ env.DOCKER_IMAGE }}' : image)
      -
        name: Kubectl Version
        id: kubever
        uses: dysnix/ws-action-parse-semver@upgrade
        with:
          string: '${{ github.event.inputs.version }}'
          extractor_regex: '${{ env.VERSION_REGEX }}'
          extractor_group: 2
      - name: Ouptuts
        run: |
          echo '${{ toJSON(steps.kubever.outputs) }}'

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: [setup]

    strategy:
      matrix:
        flavor: [default, gcloud]
        include:
          - flavor: default
            image: alpine
          - flavor: gcloud
            image: google/cloud-sdk:alpine
            suffix: -gcloud

    steps:
      - uses: actions/checkout@v2
      -
        uses: dysnix/find-latest-tag@v1
        id: latest
        with:
          compared-to-tag: ${{ github.ref }}
          repository: ${{ github.repository }}
      -
        uses: dysnix/find-latest-tag@v1
        id: latestMinor
        with:
          regex: ${{ needs.setup.outputs.minor_version }}
          compared-to-tag: ${{ github.ref }}
          repository: ${{ github.repository }}
      -
        uses: actions/github-script@v4
        id: set
        if: steps.latest.outputs.older == 'false'
        with:
          script: |
            core.setOutput('latestValue', '${{ matrix.flavor }}' !== 'default' ?
              '${{ matrix.flavor }}' : 'latest'
            );
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ needs.setup.outputs.image }}
          flavor: |
            latest=false
            suffix=${{ matrix.suffix }}
          tags: |
            type=semver,pattern=v{{version}},value=${{ needs.setup.outputs.version }}
            type=semver,pattern=v{{version}},value=${{ needs.setup.outputs.version }},suffix=${{ matrix.suffix }}-${{ needs.setup.outputs.release_id }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ needs.setup.outputs.version }},suffix=${{ matrix.suffix }},enable=${{ steps.findMinor.outputs.older == 'false' }}
            type=raw,value=${{ steps.set.outputs.latestValue }},suffix=
